# Generated by Django 6.0.2 on 2026-02-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Cpassword',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
