# Generated by Django 6.0.2 on 2026-02-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee_cpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dn', models.CharField(max_length=50)),
                ('Dd', models.CharField(max_length=100)),
                ('Dc', models.CharField(max_length=30)),
                ('Dh', models.CharField(max_length=50)),
            ],
        ),
    ]
