# Generated by Django 6.0.2 on 2026-02-20 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='Dd',
            new_name='Dep_desc',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='Dh',
            new_name='Dep_head',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='Dn',
            new_name='Dep_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='Dc',
        ),
    ]
