# Generated by Django 6.0.2 on 2026-02-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_dd_department_dep_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Dep_head',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='department',
            name='Dep_name',
            field=models.CharField(max_length=30),
        ),
    ]
