# Generated by Django 6.0.2 on 2026-02-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_department_dep_head_alter_department_dep_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='Dep_desc',
            new_name='Dep_d',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='Dep_head',
            new_name='Dep_h',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='Dep_name',
            new_name='Dep_n',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Password',
            new_name='Code',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Gender',
            new_name='Dept',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Cpassword',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Qualification',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='State',
        ),
        migrations.AddField(
            model_name='employee',
            name='Image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Contact',
            field=models.IntegerField(),
        ),
    ]
