# Generated by Django 6.0.2 on 2026-02-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_query_alter_employee_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Query',
            new_name='EmpQuery',
        ),
    ]
