# Generated by Django 6.0.2 on 2026-02-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_query_empquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='empquery',
            name='Reply',
            field=models.TextField(null=True),
        ),
    ]
