# Generated by Django 6.0.2 on 2026-02-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_empquery_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empquery',
            name='Status',
            field=models.CharField(default='pending'),
        ),
    ]
