# Generated by Django 6.0.2 on 2026-02-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_empquery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empquery',
            name='Status',
            field=models.CharField(default='pending'),
        ),
    ]
