# Generated by Django 6.0.2 on 2026-03-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_empquery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_desc', models.CharField(max_length=50)),
                ('item_price', models.CharField(max_length=50)),
                ('item_image', models.ImageField(upload_to='')),
                ('item_color', models.CharField(max_length=30)),
                ('item_categery', models.CharField(max_length=50)),
                ('item_quantity', models.CharField(max_length=50)),
            ],
        ),
    ]
